# Generated by Django 4.0 on 2022-01-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_device_alter_device_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='posters',
            field=models.ImageField(blank=True, upload_to='D:\\Проекты\\Food_city\\media', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='task',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.device', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='task',
            name='img_foto',
            field=models.ImageField(blank=True, upload_to='D:\\Проекты\\Food_city\\media', verbose_name='Фото'),
        ),
    ]
