# Generated by Django 4.0 on 2022-01-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_posters_alter_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tex_description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Техническое описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание товара'),
        ),
    ]
