# Generated by Django 4.0 on 2022-02-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_task_options_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.CharField(max_length=20, verbose_name='Цена'),
        ),
    ]
