# Generated by Django 4.0 on 2022-02-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Товар')),
                ('product_price', models.CharField(max_length=20, verbose_name='Цена')),
                ('quantity', models.CharField(max_length=10, verbose_name='Кол-во')),
                ('total_porice', models.CharField(max_length=20, verbose_name='Итого')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
