# Generated by Django 4.0 on 2022-02-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_cartitem_cartaddproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartAddProduct',
            new_name='ProductCartAdd',
        ),
    ]
