# Generated by Django 4.0 on 2022-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_productcartadd_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcartadd',
            name='product_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Товар'),
        ),
    ]
