# Generated by Django 4.0 on 2022-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_productcartadd_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcartadd',
            name='product_poster',
            field=models.ImageField(blank=True, upload_to='D:\\Проекты\\Food_city\\media', verbose_name='Фото'),
        ),
    ]
